In [1]:
import numpy as np
from gensim.models import Word2Vec
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

In [2]:
f=open('xx.txt','r',encoding='utf8')
text=f.read()
t_list=text.split('\n')

corpus=[]
for cumle in t_list:
    corpus.append(cumle.split())

In [3]:
print(corpus[0:3])

[['gelmek', 'varmak', 'ulaşmak']]


In [4]:
model=Word2Vec(corpus,size=1,window=5,min_count=0,sg=1)

In [5]:
model.wv['gelmek']

array([-0.07639544], dtype=float32)

In [6]:
model.wv['varmak']

array([-0.46605998], dtype=float32)

In [7]:
model.wv['varmak']

array([-0.46605998], dtype=float32)